<?php

/**
 * @file
 * asc_egg.module
 */

/**
 * Implements hook_user()
 */
function asc_egg_hook_user ($op) {
  if ($op == "login") {
    asc_egg_report("Login");
  }
}

/**
 * Implements hook_user()
 */
function asc_egg_hook_nodeapi (&$node, $op) {
  if ($op == "login") {
    asc_egg_report("Node Insert");
  }
}


function asc_egg_report($op) {
  $data = array("name" => $op, "service" => "Nova", "timestamp" => date('c'));
  $data_string = json_encode($data);

  $ch = curl_init('http://egg.asc.ohio-state.edu/events');
  curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST");
  curl_setopt($ch, CURLOPT_POSTFIELDS, $data_string);
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
  curl_setopt($ch, CURLOPT_HTTPHEADER, array(
    'Content-Type: application/json',
    'Content-Length: ' . strlen($data_string))
  );

  $result = curl_exec($ch);
}
